apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
  namespace: edx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver
        namespace: edx
    spec:
      containers:
      - name: webserver
        image: nginx:alpine
        ports:
        - containerPort: 80
